site_name: Argo CD - Declarative GitOps CD for Kubernetes
repo_url: https://github.com/argoproj/argo-cd
strict: true
theme:
  name: material
  palette:
    primary: teal
  font:
    text: 'Work Sans'
  logo: 'assets/logo.png'
  favicon: 'assets/favicon.png'
  language: en-custom
  custom_dir: overrides
extra_javascript:
- assets/versions.js
extra_css:
- assets/versions.css
google_analytics:
- 'UA-105170809-2'
- 'auto'

markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
  - Overview: index.md
  - Concepts & Terminology: basics/terminology.md
  - Getting started: 
    - Server installation: getting_started/install.md
    - CLI installation: getting_started/install_cli.md
    - First steps: getting_started/first_steps.md
  - Basics:
    - Applications: 
      - Overview: basics/apps/overview.md
      - Source: basics/apps/source.md
      - Destination: basics/apps/destination.md
      - State: basics/apps/state.md
      - Managing Applications: basics/apps/manage.md
    - Clusters:
      - Internal: basics/clusters/internal.md
      - External clusters: basics/clusters/external.md
      - Managing clusters: basics/clusters/manage.md
    - Repositories: 
      - Overview: basics/repos/index.md
      - Authentication: basics/repos/auth.md
      - Managing Repositories: basics/repos/manage.md 
      - Repos: basics/repositories.md
    - Projects: 
      - Overview: basics/projects/overview.md
      - Settings: basics/projects/settings.md
      - Roles: basics/projects/roles.md
    - Tools: 
      - Overview: basics/tools.md
      - Helm: basics/tools/helm.md
      - Kustomize: basics/tools/kustomize.md
      - JSonnet: basics/tools/jsonnet.md
      - Third-party tools: basics/tools/custom.md
    - Syncing:
      - Sync & Sync policies: basics/syncing.md
      - Tracking strategies: basics/tracking.md
    - Access control: basics/rbac.md
  - Advanced topics:
    - Application Health Customization: advanced/health.md
    - Diffing Customization: advanced/diffing.md
    - Git Webhooks: advanced/git_webhooks.md
    - GnuPG commit verification: advanced/gnupg.md
    - Resource Hooks: advanced/hooks.md
    - Sync Phases & Sync Waves: advanced/sync_waves.md
    - Sync Windows: advanced/sync_windows.md
  - Operations & Maintenance:
    - Architectural Overview: operations/index.md
    - Backup & Restore: operations/backup_restore.md
    - High-Availability: operations/ha.md
    - Ingress configuration:
      - Overview: operations/ingress/index.md
      - Ambassador: operations/ingress/ambassador.md
      - AWS ALB and ELB: operations/ingress/aws.md
      - Contour: operations/ingress/contour.md
      - Nginx: operations/ingress/nginx.md
      - Traefik: operations/ingress/traefik.md
    - Local users: operations/users.md
    - Security: operations/security.md
    - Single Sign On (SSO): operations/sso/overview.md
    - Upgrading: operations/upgrading.md
  - Troubleshooting:
    - Performance: troubleshooting/performance.md
    - Common Issues: troubleshooting/common-issues.md
  - Reference:
    - Custom Resource Definitions:
      - Application CRD: reference/crd/application.md
      - AppProject CRD: reference/crd/appproject.md
    - Configuration:
      - argocd-cm: reference/config/argocd-cm.md
      - argocd-secret: reference/config/argocd-secret.md
      - argocd-ssh-known-hosts-cm: reference/config/argocd-ssh-known-hosts-cm.md
      - argocd-tls-certs-cm: reference/config/argocd-tls-certs-cm.md
      - argocd-gpg-keys-cm: reference/config/argocd-gpg-keys-cm.md
      - cluster-secret: reference/config/cluster-secret.md
    - CLI usage:
      - argocd: reference/cli/argocd.md
      - argocd-util: reference/cli/argocd-util.md
    - Server workload parametrization:
      - argocd-server: reference/server/argocd-server.md
      - argocd-repo-server: reference/server/argocd-repo-server.md
      - argocd-application-controller: reference/server/argocd-application-controller.md
  - FAQ: faq.md
  - Community: community.md
  - Releases ⧉: https://github.com/argoproj/argo-cd/releases
  - Blog ⧉: https://blog.argoproj.io/
